# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inverstors-social-network' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for inverstors-social-network

  pod 'SwiftChart'

  target 'inverstors-social-networkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'inverstors-social-networkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
